### ISSUE TITLE
How to change .cube3 PLA to ABS

### ISSUE THREAD

**Issue by frchico** [buddybu/Cube3Editor#1]
Hello, could you help me modify a file so that it prints ABS?  

My printer only has the PLA cartridge and is no longer counting the quantity.  In your solution I open the Cube print program, choose the side and color it identifies through the refill chip (PLA) and then what do I do?

Tks.

**Comment by buddybu** [comment]
I apologize, I did not see this earlier.  
to do this, all you have to do is to make sure that the temperatures match your ABS.  You don't actually have to change the type of filament, in fact, if your cartridge is PLA, leave the material in the CUBE3 file as PLA, then adjust the temperatures in the tool to match your ABS.  If you can post a screenshot of the tool with your model loaded and the temperature range of your ABS, I can assist in getting that set up.

**Comment by buddybu** [comment]
If you want a prebuilt version, please feel free to visit:

https://drive.google.com/open?id=1gdMXDzmCjakj9qWiMbmhQ_f28-DhOI6e

**Comment by buddybu** [comment]
I would also suggest posting questions at 

http://www.print3dforum.com/showthread.php/2098-Cube3-File-Editor

I am quite active there.
